#!/usr/bin/sh

echo "[install requirements]"
pip install -r requirements.txt
echo "[register]"
./register
echo "[copy files]"
cp data/json/settings.json $MCPYPATH/settings.json
if test ! -d $MCPYPATH/save
then
	mkdir $MCPYPATH/save
else
	echo "install: $MCPYPATH/save existed"
fi
if test ! -d $MCPYPATH/screenshot
then
	mkdir $MCPYPATH/screenshot
else
	echo "install: $MCPYPATH/screenshot existed"
fi
