#!/usr/bin/python3

from time import time
from random import randint
from re import match
from os import path
from json import dump

if __name__ == '__main__':
    if not path.isfile('resource/json/player.json'):
        player_id = hex(int(time() * 100) * randint(1024, 8192) // randint(16, 64))[2:]
        print('Your id is %s, do not change it' % player_id)
        player_name = ''
        while not match(r'^([a-z]|[A-Z]|_)\w+$', player_name):
            player_name = input('Your name: ')
        dump({'id': player_id, 'name': player_name}, open('resource/json/player.json', 'w+'), indent='\t')
        print('Regsitered successfully, you can use your id to play multiplayer game!')
    else:
        print('You have regsitered!')
        exit(1)
